---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: kind-aws-deprovision
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.44.x"
    tekton.dev/categories: infrastructure
    tekton.dev/tags: infrastructure, aws, kind
    tekton.dev/displayName: "Kind Cloud Single Node - Destroy"
    tekton.dev/platforms: "linux/amd64, linux/arm64"
    mapt/version: "v0.9.1"
spec:
  description: |
    Tears down a Kind cluster that was previously provisioned on AWS using the Mapt CLI.

    This task is designed to safely and efficiently clean up cloud infrastructure created for ephemeral Kubernetes environments,
    typically used in CI/CD pipelines or short-lived testing environments.

    It ensures the following:
    - Proper AWS credentials are used to authenticate the delete operation
    - Cleanup is scoped to a specific environment ID to avoid accidental deletions
    - Works seamlessly with previous `kind-aws-provision` task executions
    - Supports a `debug` mode to enable verbose output for troubleshooting. !!WARNING!! Using debug mode can expose credentials.

    Use this task in any workflow where you want to ensure that your test environments don't linger and incur unnecessary cloud costs.

  volumes:
    - name: aws-credentials
      secret:
        secretName: $(params.secret-aws-credentials)
    - name: workdir
      emptyDir: {}
    - name: konflux-test-infra-volume
      secret:
        secretName: konflux-test-infra

  stepTemplate:
    env:
      - name: KUBECONFIG
        value: /var/workdir/.kube/config
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir

  params:
    - name: secret-aws-credentials
      description: |
        K8S secret holding the aws credentials. Secret should be accessible to this task.

        ---
        apiVersion: v1
        kind: Secret
        metadata:
          name: aws-${name}
        type: Opaque
        data:
          access-key: ${access_key}
          secret-key: ${secret_key}
          region: ${region}
          bucket: ${bucket}
    - name: id
      description: |
        A unique identifier for the Kind environment you want to destroy. This must match the ID used during creation.
    - name: debug
      description: |
        If set to `true`, enables verbose output and displays command execution details.
        Use only in secure environments as it may expose sensitive credentials.
      default: 'false'
    - name: pipeline-aggregate-status
      type: string
      description: |
        The status of the pipeline (e.g., Succeeded, Failed, Completed, None).
      default: None
    - name: cluster-access-secret
      type: string
      description: |
        The name of the secret containing the kubeconfig to access the target cluster.
    - name: namespace
      description: |
        Namespace where the kubeconfig secret is located.
    - name: oci-container
      type: string
      description: |
        The ORAS container registry URI where artifacts will be stored.

  steps:
    - name: get-kubeconfig
      image: quay.io/konflux-ci/tekton-integration-catalog/utils:latest
      onError: continue
      workingDir: /var/workdir
      script: |
        #!/bin/bash
        set -euo pipefail

        echo "[INFO] Retrieving kubeconfig from secret: $(params.cluster-access-secret) in namespace: $(params.namespace)"
        KUBECONFIG_B64=$(kubectl get secret "$(params.cluster-access-secret)" -n "$(params.namespace)" -o jsonpath='{.data.kubeconfig}' || true)

        if [[ -z "$KUBECONFIG_B64" ]]; then
          echo "[ERROR] Kubeconfig not found in secret $(params.cluster-access-secret) in namespace $(params.namespace)."
          exit 1
        fi

        mkdir -p /var/workdir/.kube
        echo "$KUBECONFIG_B64" | base64 -d > /var/workdir/.kube/config
        chmod 400 /var/workdir/.kube/config

        echo "[INFO] Verifying access to the target cluster..."
        kubectl cluster-info

    - name: collect-artifacts
      workingDir: /workspace/cluster-artifacts
      onError: continue
      image: quay.io/konflux-qe-incubator/konflux-qe-tools:latest
      script: |
        #!/bin/sh

        curl -sSL https://raw.githubusercontent.com/konflux-ci/tekton-integration-catalog/main/scripts/gather-extra.sh | bash
      when:
        - input: $(params.pipeline-aggregate-status)
          operator: notin
          values: ["Succeeded"]

    - name: secure-push-oci
      onError: continue
      ref:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/tekton-integration-catalog.git
          - name: revision
            value: main
          - name: pathInRepo
            value: stepactions/secure-push-oci/0.1/secure-push-oci.yaml
      params:
        - name: workdir-path
          value: /workspace
        - name: oci-ref
          value: $(params.oci-container)
        - name: credentials-volume-name
          value: konflux-test-infra-volume
      when:
        - input: $(params.pipeline-aggregate-status)
          operator: notin
          values: ["Succeeded"]

    - name: destroy
      image: quay.io/redhat-developer/mapt:v0.9.1
      volumeMounts:
        - name: aws-credentials
          mountPath: /opt/aws-credentials
      script: |
        #!/bin/sh
        set -euo pipefail
        if [[ $(params.debug) == "true" ]]; then set -xeuo pipefail; fi

        export AWS_ACCESS_KEY_ID=$(cat /opt/aws-credentials/access-key)
        export AWS_SECRET_ACCESS_KEY=$(cat /opt/aws-credentials/secret-key)
        export AWS_DEFAULT_REGION=$(cat /opt/aws-credentials/region)
        BUCKET=$(cat /opt/aws-credentials/bucket)

        cmd="mapt aws kind destroy "
        cmd+="--project-name kind-$(params.id) "
        cmd+="--backed-url s3://${BUCKET}/mapt/kind/$(params.id) "
        eval "${cmd}"

      computeResources:
        requests:
          memory: "200Mi"
          cpu: "100m"
        limits:
          memory: "600Mi"
          cpu: "300m"
