apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: git-clone
spec:
  description: >-
    This StepAction clones a Git repository into a specified directory. It fetches the source code from the given repository URL 
    and checks out the specified Git revision (commit SHA). The code is stored in a volume mounted to the pipeline, which can be used 
    for subsequent steps
  params:
    - name: repository-url
      type: string
      description: "The name or URL of the source code repository (e.g., 'github.com/org/repo')."
    - name: revision
      type: string
      description: "The Git revision (commit SHA) from which the test pipeline is originating."
    - name: source-code-volume
      type: string
      description: "The name of the volume where to store the source code when cloning."
  volumeMounts:
    - name: $(params.source-code-volume)
      mountPath: /source-code
  env:
    - name: REPOSITORY_URL
      value: $(params.repository-url)
    - name: REVISION
      value: $(params.revision)
    - name: CHECKOUT_DIR
      value: "/source-code"
  image: quay.io/konflux-ci/git-clone@sha256:4e53ebd9242f05ca55bfc8d58b3363d8b9d9bc3ab439d9ab76cdbdf5b1fd42d9
  script: |
    #!/bin/sh
    set -euo pipefail

    /ko-app/git-init \
      -url="${REPOSITORY_URL}" \
      -revision="${REVISION}" \
      -path="${CHECKOUT_DIR}"
