name: Label Approved PR with Approved and LGTM

on:
  pull_request_review:
    types: [submitted]

jobs:
  label_when_approved:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    if: github.event.review.state == 'approved'
    steps:
      - name: Add approved and lgtm labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['approved', 'lgtm']
            })
